run:
  timeout: 5m
  build-tags:
    - linux

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gosec
    - revive
    - bodyclose

issues:
  exclude-dirs:
    - ebpf
  exclude-rules:
    - path: pkg/kubedagger/
      linters:
        - errcheck
        - unused
        - gosec
        - gocritic
    - path: _test\.go
      linters:
        - gosec
        - gocritic
    - path: pkg/agent/modules/
      linters:
        - gosec
    - path: pkg/antiforensics/
      linters:
        - gosec
    - path: pkg/cloudevasion/
      linters:
        - gosec
    - path: pkg/covert/
      linters:
        - gosec
    - path: pkg/polymorph/
      linters:
        - gosec
    - path: pkg/cloudexploit/
      linters:
        - gosec
    - path: pkg/webhook/
      linters:
        - gosec
    - path: cmd/kubedagger-client/
      linters:
        - gocritic
        - gosec
    - path: cmd/kubedagger-operator/
      linters:
        - gocritic
    - path: cmd/demo/
      linters:
        - gosec

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
  gosec:
    excludes:
      - G104
      - G115
      - G304
      - G402
  revive:
    rules:
      - name: exported
        disabled: true
  gocritic:
    disabled-checks:
      - ifElseChain
      - assignOp
      - singleCaseSwitch
      - unslice
      - commentFormatting
      - dupBranchBody
