run:
  timeout: 5m
  build-tags:
    - linux

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gosec
    - revive
    - bodyclose

issues:
  exclude-dirs:
    - ebpf
  exclude-rules:
    - path: pkg/kubedagger/
      linters:
        - errcheck
        - unused
        - gosec
    - path: _test\.go
      linters:
        - gosec

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
  gosec:
    excludes:
      - G104
      - G304
  revive:
    rules:
      - name: exported
        disabled: true
