run:
  timeout: 5m
  build-tags:
    - linux

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple

issues:
  exclude-dirs:
    - ebpf
  exclude-rules:
    - path: pkg/kubedagger/
      linters:
        - errcheck
        - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
